package com.chaykin.jasper.core.annotation;

/**
 * Defines the page orientation for the blank JRXML template generated by the annotation
 * processor when {@link GenerationMode#CREATE} is used or when no existing template is found.
 *
 * <p>The orientation is declared per report or subreport class and controls which blank
 * template is used as the starting point for JRXML generation. It has no effect on
 * existing templates in {@link GenerationMode#INJECT} mode when the template already exists.</p>
 *
 * @see JasperModularReport#orientation()
 * @see JasperSubreport#orientation()
 */
public enum PageOrientation {

    /**
     * Portrait orientation — default.
     * Uses {@code Portrait.jrxml} as the starting template.
     */
    PORTRAIT,

    /**
     * Landscape orientation.
     * Uses {@code Landscape.jrxml} as the starting template.
     */
    LANDSCAPE
}
