package com.chaykin.jasper.core.annotation;

/**
 * Page orientation for the blank JRXML template generated by the annotation processor.
 */
public enum PageOrientation {

    /**
     * Portrait orientation (default).
     */
    PORTRAIT,

    /**
     * Landscape orientation.
     */
    LANDSCAPE
}
